src/DN.ControleUniversidade.Presentation.Mvc/Controllers/AlunoController.cs
using DN.ControleUniversidade.Application.Interfaces;
using DN.ControleUniversidade.Application.ViewModels.Aluno;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DN.ControleUniversidade.Presentation.Mvc.Controllers
{
    public class AlunoController : Controller
    {
        private readonly IAlunoAppService _alunoAppService;

        public AlunoController(IAlunoAppService alunoAppService)
        {
            _alunoAppService = alunoAppService;
        }
        // GET: Aluno
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(NovoAlunoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _alunoAppService.CadastrarNovoAluno(model);

                if (result.IsValid)
                    return RedirectToAction("Index");
                else
                {
                    foreach (var item in result.Erros)
                        ModelState.AddModelError("", item.Message);
                }

            }
            return View(model);
        }

    }
}

src/DN.ControleUniversidade.Presentation.Mvc/Controllers/CursoController.cs
using DN.ControleUniversidade.Application.Interfaces;
using DN.ControleUniversidade.Application.ViewModels.Curso;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DN.ControleUniversidade.Presentation.Mvc.Controllers
{
    public class CursoController : Controller
    {
        private readonly ICursoAppService _cursoAppService;
        private readonly ITipoCursoAppService _tipoCursoAppService;
        public CursoController(ICursoAppService cursoAppService, ITipoCursoAppService tipoCursoAppService)
        {
            _cursoAppService = cursoAppService;
            _tipoCursoAppService = tipoCursoAppService;
        }

        public ActionResult Index()
        {
            var model = _cursoAppService.ListarGrid();
            return View(model);
        }

        public ActionResult Cadastrar()
        {
            var model = new NovoCursoViewModel();
            model.TiposCurso = PreencherTipoCurso();
            model.Ativo = false;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(NovoCursoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _cursoAppService.CadastrarNovoCurso(model);

                if (result.IsValid)
                    return RedirectToAction("Index");
                else
                {
                    foreach (var item in result.Erros)
                        ModelState.AddModelError("", item.Message);
                }

            }
            model.TiposCurso = PreencherTipoCurso();
            return View(model);
        }

        public ActionResult Editar(Guid cursoId)
        {
            var model = _cursoAppService.ObterParaEditar(cursoId);
            model.TiposCurso = PreencherTipoCurso();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(EdicaoCursoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var result = _cursoAppService.EditarCurso(model);

                if (result.IsValid)
                    return RedirectToAction("Index");
                else
                {
                    foreach (var item in result.Erros)
                        ModelState.AddModelError("", item.Message);
                }

            }
            model.TiposCurso = PreencherTipoCurso();
            return View(model);
        }

        [OutputCache(Duration = 300, VaryByParam = "none")]
        [NonAction]
        private IEnumerable<SelectListItem> PreencherTipoCurso()
        {
            return _tipoCursoAppService.ListarTodos()
            .Select(x => new SelectListItem
            {
                Text = x.Descricao,
                Value = x.TipoCursoId.ToString()
            });
        }




    }
}

src/DN.ControleUniversidade.Presentation.Mvc/Controllers/HomeController.cs
using System.Web.Mvc;

namespace DN.ControleUniversidade.Presentation.Mvc.Controllers
{
    public class HomeController : Controller
    {
       
        public ActionResult Index()
        {

            return View();
        }
    }
}

src/DN.ControleUniversidade.Presentation.Mvc/Views/Aluno/Cadastrar.cshtml
@model DN.ControleUniversidade.Application.ViewModels.Aluno.NovoAlunoViewModel

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar Novo Aluno</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Senha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmarSenha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmarSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmarSenha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Ativo)  Ativo/Inativo
                    @Html.ValidationMessageFor(model => model.Ativo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-info" />
                <input type="button" value="Voltar" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/DN.ControleUniversidade.Presentation.Mvc/Views/Curso/Cadastrar.cshtml
@model DN.ControleUniversidade.Application.ViewModels.Curso.NovoCursoViewModel
@{
    ViewBag.Title = "Cadastrar";
}
<h2>Cadastrar Novo Curso</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCursoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoCursoId, Model.TiposCurso, "--Selecione--", new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.TipoCursoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-2">
                <div class="checkbox">
                    <label>
                        @Html.EditorFor(model => model.Ativo) Ativo/Inativo
                    </label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-info" />
                <input type="button" value="Voltar" class="btn btn-danger" id="btnVoltar" />
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $("#btnVoltar").click(function () {
            window.location = '@Url.Action("Index", "Curso")';
        });
    </script>
}

src/DN.ControleUniversidade.Presentation.Mvc/Views/Curso/Editar.cshtml
@model DN.ControleUniversidade.Application.ViewModels.Curso.EdicaoCursoViewModel   

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(x => x.CursoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCursoId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TipoCursoId, Model.TiposCurso, "--Selecione--", new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.TipoCursoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ativo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-xs-2">
                <div class="checkbox">
                    <label>
                        @Html.EditorFor(model => model.Ativo) Ativo/Inativo
                    </label>
                </div>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/DN.ControleUniversidade.Presentation.Mvc/Views/Curso/Index.cshtml
@model IEnumerable<DN.ControleUniversidade.Application.ViewModels.Curso.GridCursoViewModel>

@{
    ViewBag.Title = "Cursos";
}

<h2>Cursos</h2>

<p>
    @Html.ActionLink("Novo Curso", "Cadastrar")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TipoCurso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ativo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCadastro)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoCurso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ativo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataCadastro)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { cursoId = item.CursoId })
            </td>
        </tr>
    }

</table>

src/DN.ControleUniversidade.Presentation.Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
       
    </div>
</div>

src/DN.ControleUniversidade.Presentation.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Controle Universidade</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Controle Universidade", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cursos", "Index", "Curso")</li>
                    <li>@Html.ActionLink("Turmas", "Index", "Curso")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Aluno<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Cadastrar", "Cadastrar", "Aluno")</li>
                            <li><a href="#">Pesquisar</a></li>
                            <li><a href="#">Alterar Senha</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Controle Universidade</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>